name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Inject Webhook URL
        run: echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" > .env

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Uploads the entire repository

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
